$ANSIBLE_VAULT;1.1;AES256
38656132303538353830613734313133393439653465366438666266386130353633396666613966
3438613338353630383061313665343366353264326261370a336236646362373162663138363762
37626233333534353736343066313262653735343064393165383637653636383936356239613139
3163653165313966610a373265313365653538323131373965653430393838316563376434643230
38643632366332366664356530383733396339663733663564613861646437303162643066653638
34616165326337383738633938396565303866616636386464666466353931396165636236383464
64643263643533393761313762383038396634396336643963313962386664333138336362323233
62323961343266336664313133393135393163336339373738636532383233323161373333376636
62303461323031623266376231393062666664633363343162326566396266333530613736646561
61626364633063666339376333323064626665636137303439666665643832623839346134633239
30643433623265623432333739613265343462613737333531666132393431353338616562366337
38303636636135306665383635333461353763636537343563363134633166633764313737376264
66366262363936333737303039343639653164626138373265326538623830346130613766373235
37643862306664356463316666386439333930376261323764393936346235346563393339613665
646134633564343535616661636536316461
